// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjj9or1ZekZkkG1SA2y9dCObTC7MO9MCU',
    appId: '1:821203465096:web:62f9664b3cc7ac79fb403d',
    messagingSenderId: '821203465096',
    projectId: 'my-school-application-8963c',
    authDomain: 'my-school-application-8963c.firebaseapp.com',
    storageBucket: 'my-school-application-8963c.appspot.com',
    measurementId: 'G-ZPYWQXQVRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIJ27WU_Ks0WRVC9UYGh8ymJNx-MUODO8',
    appId: '1:821203465096:android:3b4f38bc3b020392fb403d',
    messagingSenderId: '821203465096',
    projectId: 'my-school-application-8963c',
    storageBucket: 'my-school-application-8963c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcUix2XnlyzPFTgh9ofOafg7GhUZEOkJI',
    appId: '1:821203465096:ios:5ed780b3990bef70fb403d',
    messagingSenderId: '821203465096',
    projectId: 'my-school-application-8963c',
    storageBucket: 'my-school-application-8963c.appspot.com',
    iosBundleId: 'com.example.schoolApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcUix2XnlyzPFTgh9ofOafg7GhUZEOkJI',
    appId: '1:821203465096:ios:b9d92b37ffcabfd9fb403d',
    messagingSenderId: '821203465096',
    projectId: 'my-school-application-8963c',
    storageBucket: 'my-school-application-8963c.appspot.com',
    iosBundleId: 'com.example.schoolApplication.RunnerTests',
  );
}
